---
# site info
baseurl: ""
description: >
  Fully qualified and professional tree surgeon based in Kenilworth, UK.
  Covering surrounding areas.
email: a.roddy (at) adrtreesurgery (dot) co (dot) uk
goatcounter_site: adrtreesurgery
remote_theme: pages-themes/hacker
repository: paddyroddy/adr-tree-surgery-website
title: A.D.R Tree Surgery
url: https://www.adrtreesurgery.co.uk

# social media
facebook_username: ADRTreeSurgery
phone_number: +44-7397-989-051

# medida gallery
media_per_col: 4

# disable redirects.json
redirect_from:
  json: false

# plugins
plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
